#!/usr/bin/env bash
# install nginx on web-01

	sudo apt-get update
	sudo apt-get -y install nginx
 	sudo ufw allow "Nginx HTTP"

	echo "Hello World!" | sudo tee /var/www/html/index.html


SERVER_CONFIG=\
	
 "server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /var/www/html;
	  index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
	  try_files $uri $uri/ =404;
        }


  location = /redirect_me {
                return 301 https://youtu.be/mMJ3Gogi2Qk;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default" 

sudo service nginx restart
